version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.1
    commands:
      - echo "Installing Fastlane..."
      - gem install fastlane --no-document

  pre_build:
    commands:
      - echo "Checking Fastlane version..."
      - fastlane --version
      - echo "Verifying directory structure..."
      - ls -R

  build:
    commands:
      - echo "Building IPA using Fastlane"
      - fastlane beta   # Make sure `beta` lane generates .ipa into ./build/ios/ipa/

  post_build:
    commands:
      - echo "Uploading IPA to S3..."
      - ls ./build/ios/ipa/
      - |
        for ipa_file in $(find ./build/ios/ipa -name "*.ipa"); do
          echo "Uploading $ipa_file"
          aws s3 cp "$ipa_file" "s3://boatcicd/releases/$(basename "$ipa_file")"
        done

artifacts:
  files:
    - build/ios/ipa/**/*.ipa
  discard-paths: yes
