version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.1
    commands:
      - echo "Installing Fastlane"
      - gem install fastlane
      - echo "Fastlane installed"

  pre_build:
    commands:
      - echo "Checking project files"
      - fastlane --version
      - ls -al

  build:
    commands:
      - echo "Building IPA using Fastlane"
      - fastlane build_ios   # Customize with your Fastlane lane name

  post_build:
    commands:
      - echo "Uploading IPA to S3"
      - ls -a
      - aws s3 cp ./build/ios/ipa/YourApp.ipa s3://boatcicd/releases/YourApp.ipa

artifacts:
  files:
    - build/ios/ipa/YourApp.ipa
