version: 0.2

phases:
  install:
    commands:
      - echo "Installing Bundler and Fastlane..."
      - '[ -f Gemfile ] || (bundle init && bundle add fastlane)'
      - bundle install
  build:
    commands:
      - echo "Running Fastlane build..."
      - bundle exec fastlane beta
      - echo "Uploading IPA to S3..."
      - aws s3 cp ./build/sample_app.ipa s3://boatcicd/
artifacts:
  files:
    - build/sample_app.ipa
