version: 0.2

env:
  secrets-manager:
    APPLE_API_KEY: "ios/appstore/credentials:APPLE_API_KEY"
    APPLE_API_ISSUER_ID: "ios/appstore/credentials:APPLE_API_ISSUER_ID"
    APPLE_API_KEY_ID: "ios/appstore/credentials:APPLE_API_KEY_ID"
  variables:
    LANG: en_US.UTF-8

phases:
  install:
    runtime-versions:
      ruby: 3.2
    commands:
      - echo Installing dependencies...
      - gem install bundler
      - bundle install
  pre_build:
    commands:
      - echo Pre-build phase...
      - bundle exec fastlane match development --readonly
  build:
    commands:
      - echo Building the iOS app...
      - bundle exec fastlane build
  post_build:
    commands:
      - echo Build completed.
      - mkdir -p ios-build-output
      - cp ./build/app.ipa ios-build-output/app.ipa

artifacts:
  files:
    - app.ipa
  base-directory: ios-build-output
  name: app
