version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.1
    commands:
      - echo "Installing Fastlane"
      - gem install fastlane --no-document
      - echo "Fastlane installed"

  pre_build:
    commands:
      - echo "Checking Fastlane and project structure"
      - fastlane --version
      - ls -R

  build:
    commands:
      - echo "Running Fastlane lane: beta"
      - fastlane beta   # Replace with your actual lane if named differently

  post_build:
    commands:
      - echo "Uploading IPA(s) to S3"
      - ls ./build/ios/ipa/
      - for file in $(find ./build/ios/ipa -name "*.ipa"); do
            echo "Uploading $file to S3";
            aws s3 cp "$file" "s3://boatcicd/releases/$(basename $file)";
        done

artifacts:
  files:
    - build/ios/ipa/**/*.ipa
  discard-paths: yes
