version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.1
    commands:
      - echo "Installing Fastlane"
      - gem install fastlane --no-document
      - echo "Fastlane installed"

  pre_build:
    commands:
      - echo "Checking Fastlane and project files"
      - fastlane --version
      - ls -al

  build:
    commands:
      - echo "Building IPA using Fastlane"
      - fastlane beta   # Use the existing lane that builds IPA

  post_build:
    commands:
      - echo "Uploading IPA to S3"
      - ls -al ./build/ios/ipa/
      - aws s3 cp ./build/ios/ipa/*.ipa s3://boatcicd/releases/

artifacts:
  files:
    - build/ios/ipa/*.ipa
